annotations:
  artifacthub.io/repository: disallow-service-loadbalancer
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/type: kubewarden-policy
  catalog.cattle.io/ui-component: kubewarden
  kubewarden/displayName: Disallow Service Loadbalancer
  kubewarden/mutation: "false"
  kubewarden/registry: ghcr.io
  kubewarden/repository: kubewarden/policies/disallow-service-loadbalancer
  kubewarden/resources: Service
  kubewarden/rules: |
    - apiGroups:
      - ''
      apiVersions:
      - v1
      resources:
      - services
      operations:
      - CREATE
      - UPDATE
  kubewarden/tag: v1.0.5
appVersion: 1.0.5
description: A policy that prevents the creation of Service resources of type `LoadBalancer`
home: https://github.com/kubewarden/disallow-service-loadbalancer-policy
keywords:
- service
name: disallow-service-loadbalancer
sources:
- ghcr.io/kubewarden/policies/disallow-service-loadbalancer:v1.0.5
version: 1.0.5
