annotations:
  artifacthub.io/repository: host-namespaces-psp
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/type: kubewarden-policy
  catalog.cattle.io/ui-component: kubewarden
  kubewarden/displayName: Host Namespaces PSP
  kubewarden/mutation: "false"
  kubewarden/registry: ghcr.io
  kubewarden/repository: kubewarden/policies/host-namespaces-psp
  kubewarden/resources: Pod
  kubewarden/rules: |
    - apiGroups:
      - ''
      apiVersions:
      - v1
      resources:
      - pods
      operations:
      - CREATE
      - UPDATE
    - apiGroups:
      - ''
      apiVersions:
      - v1
      resources:
      - replicationcontrollers
      operations:
      - CREATE
      - UPDATE
    - apiGroups:
      - apps
      apiVersions:
      - v1
      resources:
      - deployments
      - replicasets
      - statefulsets
      - daemonsets
      operations:
      - CREATE
      - UPDATE
    - apiGroups:
      - batch
      apiVersions:
      - v1
      resources:
      - jobs
      - cronjobs
      operations:
      - CREATE
      - UPDATE
  kubewarden/tag: v1.1.2
appVersion: 1.1.2
description: A Kubewarden policy that controls the usage of host namespaces
home: https://github.com/kubewarden/host-namespaces-psp-policy
keywords:
- psp
- container
- network
name: host-namespaces-psp
sources:
- ghcr.io/kubewarden/policies/host-namespaces-psp:v1.1.2
version: 1.1.2
