annotations:
  artifacthub.io/repository: unique-ingress-policy
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/type: kubewarden-policy
  catalog.cattle.io/ui-component: kubewarden
  kubewarden/contextAwareResources: |
    - apiVersion: networking.k8s.io/v1
      kind: Ingress
  kubewarden/displayName: Unique Ingress host
  kubewarden/mutation: "false"
  kubewarden/registry: ghcr.io
  kubewarden/repository: kubewarden/policies/unique-ingress-policy
  kubewarden/resources: Ingress
  kubewarden/rules: |
    - apiGroups:
      - networking.k8s.io
      apiVersions:
      - v1
      resources:
      - ingresses
      operations:
      - CREATE
      - UPDATE
  kubewarden/tag: v1.0.3
appVersion: 1.0.3
description: Requires all Ingress rule hosts to be unique
home: https://github.com/kubewarden/unique-ingress-policy
keywords:
- ingress
- kubewarden
name: ingress-unique-host
sources:
- ghcr.io/kubewarden/policies/unique-ingress-policy:v1.0.3
version: 1.0.3
