annotations:
  artifacthub.io/repository: psa-label-enforcer
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/type: kubewarden-policy
  catalog.cattle.io/ui-component: kubewarden
  kubewarden/displayName: PSA Label Enforcer
  kubewarden/mutation: "true"
  kubewarden/registry: ghcr.io
  kubewarden/repository: kubewarden/policies/psa-label-enforcer
  kubewarden/resources: Namespace
  kubewarden/rules: |
    - apiGroups:
      - ''
      apiVersions:
      - v1
      resources:
      - namespaces
      operations:
      - CREATE
      - UPDATE
  kubewarden/tag: v1.0.5
appVersion: 1.0.5
description: Policy to ensure that namespaces have the required PSA labels configuration
  for deployment in the cluster.
home: https://github.com/kubewarden/psa-label-enforcer-policy
keywords:
- namespace
- psa
- kubewarden
name: psa-label-enforcer
sources:
- ghcr.io/kubewarden/policies/psa-label-enforcer:v1.0.5
version: 1.0.5
