name: pkg2chart CI

on:
  push:
    branches: [main]
    paths:
      - "pkg2chart/**"
  pull_request:
    branches: [main]
    paths:
      - "pkg2chart/**"

jobs:
  test:
    name: Test and Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./pkg2chart

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version-file: ./pkg2chart/go.mod

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8.0.0
        with:
          working-directory: ./pkg2chart

      - name: Run tests
        run: go test -v ./...
